# Python data types

In [1]:
import pandas as pd
import numpy as np

## List

Store values ["Jan", "Piet", "Joris", "Korneel"] as in list.

In [2]:
names = ["Jan", "Piet", "Joris", "Korneel"]
names

['Jan', 'Piet', 'Joris', 'Korneel']

# Data Frame
Create a data frame _pirates_ with two columns, "name" and "blood_type".

In [3]:
#  blood_type     name
#           A      Jan
#           B     Piet
#          AB    Joris
#           O  Korneel

In [4]:
pirates = pd.DataFrame({"name" : names, "blood_type" : ["A","B","AB","O"]})
pirates

blood_type     name
0          A      Jan
1          B     Piet
2         AB    Joris
3          O  Korneel

Extract column bloodtype from the data frame.

In [5]:
pirates["name"]

0        Jan
1       Piet
2      Joris
3    Korneel
Name: name, dtype: object

Extract second row from the data frame.

In [6]:
pirates.iloc[2]

blood_type       AB
name          Joris
Name: 2, dtype: object

Extract names from the first and second row from the data frame.

In [7]:
pirates.iloc[:2]["name"]

0     Jan
1    Piet
Name: name, dtype: object

Add custom index (row names) to the data frame:

In [8]:
#         blood_type     name
# Big              A      Jan
# Average          B     Piet
# Small           AB    Joris
# Big              O  Korneel

In [9]:
pirates.set_index([["Big", "Average", "Small", "Big"]], inplace=True)
print(pirates)

        blood_type     name
Big              A      Jan
Average          B     Piet
Small           AB    Joris
Big              O  Korneel


Select all rows with "Big" pirates from the data frame.

In [10]:
pirates.loc["Big"]

blood_type     name
Big          A      Jan
Big          O  Korneel

# Vector

Create a sequence of numbers from 0 to 3.

In [11]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

Create a sequence of numbers from 0 to 3 as type _range_.

In [12]:
range(4)

range(0, 4)

# Matrix

Create the following 4x2 matrix _A_:

In [13]:
# 0 1
# 1 2
# 2 3
# 3 4

In [14]:
A = np.matrix([[0,1,2,3], [1,2,3,4]]).transpose()
A

matrix([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [15]:
np.matrix([range(4), range(1,4)])

matrix([[range(0, 4), range(1, 4)]], dtype=object)

Do an elementwise multiplication of $A$ by $A$ (also called Hadamard product $A \circ A$).

In [16]:
np.multiply(A, A)

matrix([[ 0,  1],
        [ 1,  4],
        [ 4,  9],
        [ 9, 16]])

Make a matrix dot product $AA^T$

In [17]:
A.dot(A.transpose())

matrix([[ 1,  2,  3,  4],
        [ 2,  5,  8, 11],
        [ 3,  8, 13, 18],
        [ 4, 11, 18, 25]])

# Quick assignment

Assign values from tuple (1,2) to variables _a_ and _b_.

In [18]:
(a,b) = (1,2)

Assign 1 to variables _a_, _b_ and _c_.

In [19]:
a = b = c = 1